/**
 * distributor.js — Upload & Distribution Scaffold
 *
 * Integrates with YouTube Shorts and Instagram Reels APIs.
 * Currently in STUB mode — logs upload actions without executing.
 *
 * In production, replace stubs with real OAuth + API calls:
 *   - YouTube: googleapis.com/youtube/v3
 *   - Instagram: graph.facebook.com/v18.0
 *
 * Usage: node distributor.js [--dry-run]
 */

require("dotenv").config();
const fs = require("fs");
const path = require("path");

const OUTPUT_DIR = path.join(__dirname, "output");
const SCHEDULE_INTERVAL_HOURS = 24;

// ─── Platform Upload Stubs ──────────────────────────────
async function uploadToYouTubeShorts(filePath, title, description, tags) {
  console.log(`   📺 [STUB] YouTube Shorts upload:`);
  console.log(`      File:  ${path.basename(filePath)}`);
  console.log(`      Title: ${title}`);
  console.log(`      Tags:  ${tags.join(", ")}`);
  console.log(`      ⏸️  Skipped (stub mode — no real API call)`);

  // In production:
  // 1. Authenticate via OAuth2 (requires client_id + client_secret + refresh_token)
  // 2. POST to https://www.googleapis.com/upload/youtube/v3/videos
  // 3. Set snippet.categoryId = 28 (Science & Tech) or appropriate
  // 4. Set status.privacyStatus = "public"
  // 5. Set status.selfDeclaredMadeForKids = false

  return { platform: "youtube_shorts", status: "stub", id: "yt_stub_" + Date.now() };
}

async function uploadToInstagramReels(filePath, caption, hashtags) {
  console.log(`   📸 [STUB] Instagram Reels upload:`);
  console.log(`      File:    ${path.basename(filePath)}`);
  console.log(`      Caption: ${caption.substring(0, 60)}...`);
  console.log(`      ⏸️  Skipped (stub mode — no real API call)`);

  // In production:
  // 1. POST to https://graph.facebook.com/v18.0/{ig-user-id}/media
  //    with { media_type: "REELS", video_url: <hosted_url>, caption: ... }
  // 2. POST to https://graph.facebook.com/v18.0/{ig-user-id}/media_publish
  //    with { creation_id: <from step 1> }

  return { platform: "instagram_reels", status: "stub", id: "ig_stub_" + Date.now() };
}

// ─── Auto-Pilot Scheduler ───────────────────────────────
async function scheduledLoop() {
  console.log("╔═══════════════════════════════════════════════════╗");
  console.log("║  📡 Distributor — Auto-Pilot Mode                    ║");
  console.log("╚═══════════════════════════════════════════════════╝\n");

  // Find the latest report
  const reportFiles = fs.readdirSync(OUTPUT_DIR)
    .filter((f) => f.startsWith("report_") && f.endsWith(".json"))
    .sort()
    .reverse();

  if (reportFiles.length === 0) {
    console.log("❌ No render reports found. Run factory.js first.");
    return;
  }

  const latestReport = JSON.parse(
    fs.readFileSync(path.join(OUTPUT_DIR, reportFiles[0]), "utf-8")
  );

  console.log(`📄 Latest report: ${reportFiles[0]}`);
  console.log(`📌 Topic: "${latestReport.topic}"\n`);

  for (const result of latestReport.results) {
    if (!result.pass) {
      console.log(`⏭️  Skipping ${result.file} — failed quality gate`);
      continue;
    }

    const filePath = path.join(OUTPUT_DIR, result.file);
    if (!fs.existsSync(filePath)) {
      console.log(`⏭️  Skipping ${result.file} — file not found`);
      continue;
    }

    const langLabel = { en: "🇺🇸", es: "🇪🇸", hi: "🇮🇳" }[result.lang] || "🌐";
    console.log(`\n${langLabel} Distributing: ${result.file}`);

    // YouTube Shorts
    await uploadToYouTubeShorts(
      filePath,
      `${latestReport.topic} | ${result.lang.toUpperCase()} #shorts`,
      `Auto-generated by AI Video Factory`,
      ["shorts", "ai", "viral", result.lang]
    );

    // Instagram Reels
    await uploadToInstagramReels(
      filePath,
      `${latestReport.topic} 🔥\n\n#viral #reels #ai #tech #trending`,
      ["viral", "reels", "ai", "tech"]
    );
  }

  console.log(`\n⏰ Auto-pilot: next cycle in ${SCHEDULE_INTERVAL_HOURS} hours`);
  console.log("   (In production, use cron/PM2/node-schedule for real scheduling)\n");
}

scheduledLoop().catch((err) => {
  console.error("💥 Distributor error:", err);
  process.exit(1);
});
